
export const GET_HEADER_REQUEST = 'GET_HEADER_REQUEST';
export const GET_HEADER_SUCCESS = 'GET_HEADER_SUCCESS';
export const GET_HEADER_FAILED = 'GET_HEADER_FAILED';

export const ADD_HEADER_REQUEST = 'ADD_HEADER_REQUEST';
export const ADD_HEADER_SUCCESS = 'ADD_HEADER_SUCCESS';
export const ADD_HEADER_FAILED = 'ADD_HEADER_FAILED';

export const UPDATE_HEADER_FAILED = 'UPDATE_HEADER_FAILED';
export const UPDATE_HEADER_REQUEST = 'UPDATE_HEADER_REQUEST';
export const UPDATE_HEADER_SUCCESS = 'UPDATE_HEADER_SUCCESS';

export const GET_SERVICE_REQUEST = 'GET_SERVICE_REQUEST';
export const GET_SERVICE_SUCCESS = 'GET_SERVICE_SUCCESS';
export const GET_SERVICE_FAILED = 'GET_SERVICE_FAILED';

export const ADD_SERVICE_REQUEST = 'ADD_SERVICE_REQUEST';
export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS';
export const ADD_SERVICE_FAILED = 'ADD_SERVICE_FAILED';

export const UPDATE_SERVICE_FAILED = 'UPDATE_SERVICE_FAILED';
export const UPDATE_SERVICE_REQUEST = 'UPDATE_SERVICE_REQUEST';
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS';

export const DELETE_SERVICE_FAILED = 'DELETE_SERVICE_FAILED';
export const DELETE_SERVICE_REQUEST = 'DELETE_SERVICE_REQUEST';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';

export const GET_STATISTIC_REQUEST = 'GET_STATISTIC_REQUEST';
export const GET_STATISTIC_SUCCESS = 'GET_STATISTIC_SUCCESS';
export const GET_STATISTIC_FAILED = 'GET_STATISTIC_FAILED';

export const ADD_STATISTIC_REQUEST = 'ADD_STATISTIC_REQUEST';
export const ADD_STATISTIC_SUCCESS = 'ADD_STATISTIC_SUCCESS';
export const ADD_STATISTIC_FAILED = 'ADD_STATISTIC_FAILED';

export const UPDATE_STATISTIC_FAILED = 'UPDATE_STATISTIC_FAILED';
export const UPDATE_STATISTIC_REQUEST = 'UPDATE_STATISTIC_REQUEST';
export const UPDATE_STATISTIC_SUCCESS = 'UPDATE_STATISTIC_SUCCESS';

export const GET_PACKAGE_REQUEST = 'GET_PACKAGE_REQUEST';
export const GET_PACKAGE_SUCCESS = 'GET_PACKAGE_SUCCESS';
export const GET_PACKAGE_FAILED = 'GET_PACKAGE_FAILED';

export const ADD_PACKAGE_REQUEST = 'ADD_PACKAGE_REQUEST';
export const ADD_PACKAGE_SUCCESS = 'ADD_PACKAGE_SUCCESS';
export const ADD_PACKAGE_FAILED = 'ADD_PACKAGE_FAILED';

export const UPDATE_PACKAGE_FAILED = 'UPDATE_PACKAGE_FAILED';
export const UPDATE_PACKAGE_REQUEST = 'UPDATE_PACKAGE_REQUEST';
export const UPDATE_PACKAGE_SUCCESS = 'UPDATE_PACKAGE_SUCCESS';

export const DELETE_PACKAGE_FAILED = 'DELETE_PACKAGE_FAILED';
export const DELETE_PACKAGE_REQUEST = 'DELETE_PACKAGE_REQUEST';
export const DELETE_PACKAGE_SUCCESS = 'DELETE_PACKAGE_SUCCESS';

export const GET_CUSTOMER_REQUEST = 'GET_CUSTOMER_REQUEST';
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';
export const GET_CUSTOMER_FAILED = 'GET_CUSTOMER_FAILED';

export const ADD_CUSTOMER_REQUEST = 'ADD_CUSTOMER_REQUEST';
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';
export const ADD_CUSTOMER_FAILED = 'ADD_CUSTOMER_FAILED';

export const UPDATE_CUSTOMER_FAILED = 'UPDATE_CUSTOMER_FAILED';
export const UPDATE_CUSTOMER_REQUEST = 'UPDATE_CUSTOMER_REQUEST';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';

export const DELETE_CUSTOMER_FAILED = 'DELETE_CUSTOMER_FAILED';
export const DELETE_CUSTOMER_REQUEST = 'DELETE_CUSTOMER_REQUEST';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';

export const GET_ADVERTISEMENT_REQUEST = 'GET_ADVERTISEMENT_REQUEST';
export const GET_ADVERTISEMENT_SUCCESS = 'GET_ADVERTISEMENT_SUCCESS';
export const GET_ADVERTISEMENT_FAILED = 'GET_ADVERTISEMENT_FAILED';

export const ADD_ADVERTISEMENT_REQUEST = 'ADD_ADVERTISEMENT_REQUEST';
export const ADD_ADVERTISEMENT_SUCCESS = 'ADD_ADVERTISEMENT_SUCCESS';
export const ADD_ADVERTISEMENT_FAILED = 'ADD_ADVERTISEMENT_FAILED';

export const UPDATE_ADVERTISEMENT_FAILED = 'UPDATE_ADVERTISEMENT_FAILED';
export const UPDATE_ADVERTISEMENT_REQUEST = 'UPDATE_ADVERTISEMENT_REQUEST';
export const UPDATE_ADVERTISEMENT_SUCCESS = 'UPDATE_ADVERTISEMENT_SUCCESS';

export const GET_ABOUT_REQUEST = 'GET_ABOUT_REQUEST';
export const GET_ABOUT_SUCCESS = 'GET_ABOUT_SUCCESS';
export const GET_ABOUT_FAILED = 'GET_ABOUT_FAILED';

export const ADD_ABOUT_REQUEST = 'ADD_ABOUT_REQUEST';
export const ADD_ABOUT_SUCCESS = 'ADD_ABOUT_SUCCESS';
export const ADD_ABOUT_FAILED = 'ADD_ABOUT_FAILED';

export const UPDATE_ABOUT_FAILED = 'UPDATE_ABOUT_FAILED';
export const UPDATE_ABOUT_REQUEST = 'UPDATE_ABOUT_REQUEST';
export const UPDATE_ABOUT_SUCCESS = 'UPDATE_ABOUT_SUCCESS';

export const GET_GRIP_REQUEST = 'GET_GRIP_REQUEST';
export const GET_GRIP_SUCCESS = 'GET_GRIP_SUCCESS';
export const GET_GRIP_FAILED = 'GET_GRIP_FAILED';

export const ADD_GRIP_REQUEST = 'ADD_GRIP_REQUEST';
export const ADD_GRIP_SUCCESS = 'ADD_GRIP_SUCCESS';
export const ADD_GRIP_FAILED = 'ADD_GRIP_FAILED';

export const UPDATE_GRIP_FAILED = 'UPDATE_GRIP_FAILED';
export const UPDATE_GRIP_REQUEST = 'UPDATE_GRIP_REQUEST';
export const UPDATE_GRIP_SUCCESS = 'UPDATE_GRIP_SUCCESS';

export const DELETE_GRIP_FAILED = 'DELETE_GRIP_FAILED';
export const DELETE_GRIP_REQUEST = 'DELETE_GRIP_REQUEST';
export const DELETE_GRIP_SUCCESS = 'DELETE_GRIP_SUCCESS';

export const GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST';
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_FAILED = 'GET_ARTICLE_FAILED';

export const ADD_ARTICLE_REQUEST = 'ADD_ARTICLE_REQUEST';
export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS';
export const ADD_ARTICLE_FAILED = 'ADD_ARTICLE_FAILED';

export const UPDATE_ARTICLE_FAILED = 'UPDATE_ARTICLE_FAILED';
export const UPDATE_ARTICLE_REQUEST = 'UPDATE_ARTICLE_REQUEST';
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';

export const DELETE_ARTICLE_FAILED = 'DELETE_ARTICLE_FAILED';
export const DELETE_ARTICLE_REQUEST = 'DELETE_ARTICLE_REQUEST';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';


