
export const GET_PREDICT_REQUEST = 'GET_PREDICT_REQUEST';
export const GET_PREDICT_SUCCESS = 'GET_PREDICT_SUCCESS';
export const GET_PREDICT_FAILED = 'GET_PREDICT_FAILED';

export const GET_OLD_TIPS_REQUEST = 'GET_OLD_TIPS_REQUEST';
export const GET_OLD_TIPS_SUCCESS = 'GET_OLD_TIPS_SUCCESS';
export const GET_OLD_TIPS_FAILED = 'GET_OLD_TIPS_FAILED';

export const ADD_PREDICT_REQUEST = 'ADD_PREDICT_REQUEST';
export const ADD_PREDICT_SUCCESS = 'ADD_PREDICT_SUCCESS';
export const ADD_PREDICT_FAILED = 'ADD_PREDICT_FAILED';

export const UPDATE_PREDICT_FAILED = 'UPDATE_PREDICT_FAILED';
export const UPDATE_PREDICT_REQUEST = 'UPDATE_PREDICT_REQUEST';
export const UPDATE_PREDICT_SUCCESS = 'UPDATE_PREDICT_SUCCESS';

export const DELETE_PREDICT_FAILED = 'DELETE_PREDICT_FAILED';
export const DELETE_PREDICT_REQUEST = 'DELETE_PREDICT_REQUEST';
export const DELETE_PREDICT_SUCCESS = 'DELETE_PREDICT_SUCCESS';
